package me.decce.transformingbase.service.transform;

import me.decce.transformingbase.constants.Constants;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldInsnNode;
import org.objectweb.asm.tree.FieldNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.analysis.Analyzer;
import org.objectweb.asm.tree.analysis.AnalyzerException;

import java.util.ArrayList;
import java.util.List;

public class CommonTransformer {
    public static final Logger LOGGER = LogManager.getLogger();
    public static final String SYNTHETIC_VALUES = "$VALUES"; // generated by the compiler (javac)
    public static final String VALUES = Constants.MOD_ID + "$VALUES";
    public static final String VALUES_METHOD_NAME = "values";
    public static final String ENUM_CLASSNAME = Type.getInternalName(Enum.class);
    public static final int ACC_PUBLIC_STATIC_FINAL = Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC | Opcodes.ACC_FINAL;

    public static boolean process(ClassNode node) {
        if (ENUM_CLASSNAME.equals(node.superName)) {
            // Enum class, add VALUES field
            EnumTransformer.processEnum(node);
            return true;
        }
        else {
            return NonEnumTransformer.processNonEnum(node);
        }
    }

    public static class EnumTransformer {
        public static void processEnum(ClassNode node) {
            String desc = "[L" + node.name + ";";
            var field = new FieldNode(ACC_PUBLIC_STATIC_FINAL, VALUES, desc, null, null);
            node.fields.add(field);
            MethodNode clinit = ASMUtil.clinitOf(node);
            // jasione$VALUES = $VALUES
            InsnList insnList = new InsnList();
            insnList.add(new FieldInsnNode(Opcodes.GETSTATIC, node.name, SYNTHETIC_VALUES, desc));
            insnList.add(new FieldInsnNode(Opcodes.PUTSTATIC, node.name, VALUES, desc));
            for (var returnInsn : ASMUtil.findReturnInsns(clinit)) {
                clinit.instructions.insertBefore(returnInsn, insnList);
            }
        }
    }

    public static class NonEnumTransformer {
        public static boolean processNonEnum(ClassNode node) {
            boolean flag = false;
            for (var methodNode : node.methods) {
                // Process all methods, return true if any of them has been transformed
                if (processMethod(methodNode, node.name)) {
                    flag = true;
                }
            }
            return flag;
        }

        public static boolean processMethod(MethodNode node, String className) {
            if (ASMUtil.CLINIT.equals(node.name)) {
                // Skip processing clinit to prevent redirecting the initialization insn that we inserted
                // static constructors are not worth optimizing anyway because they'll only be fired once on classload-
                return false;
            }
            if (node.instructions == null || node.instructions.size() == 0) {
                return false;
            }
            return rewriteSafeValuesCall(node, className);
        }

        private static boolean rewriteSafeValuesCall(MethodNode node, String className) {
            List<MethodInsnNode> valuesInsns = new ArrayList<>();
            for (var insn : node.instructions) {
                if (insn instanceof MethodInsnNode methodInsnNode &&
                        isLikelyEnumValuesCall(methodInsnNode)) {
                    valuesInsns.add(methodInsnNode);
                }
            }

            boolean rewritten = false;
            for (var valuesInsn : valuesInsns) {
                if (isSafe(node, className, valuesInsn)) {
                    String desc = valuesInsn.desc.substring(2); // ()[LEnum; -> [LEnum;
                    node.instructions.insert(valuesInsn, new FieldInsnNode(Opcodes.GETSTATIC, valuesInsn.owner, VALUES, desc));
                    node.instructions.remove(valuesInsn);
                    rewritten = true;
                }
            }
            return rewritten;
        }

        private static boolean isSafe(MethodNode node, String className, MethodInsnNode valuesInsn) {
            InterpreterEx interpreterEx = new InterpreterEx(valuesInsn);
            Analyzer<SourceValueEx> analyzer = new Analyzer<>(interpreterEx);
            try {
                analyzer.analyze(className, node);
            } catch (AnalyzerException e) {
                LOGGER.warn("Failed to analyze {}", className, e);
                return false;
            }
            return !interpreterEx.hasViolation();
        }

        public static boolean isLikelyEnumValuesCall(MethodInsnNode insn) {
            return insn.getOpcode() == Opcodes.INVOKESTATIC &&
                    insn.name.equals(VALUES_METHOD_NAME) &&
                    insn.desc.equals("()[L" + insn.owner + ";"); //TODO
        }
    }
}
