package me.decce.transformingbase.service.transform;

import me.decce.transformingbase.constants.Constants;
import me.decce.transformingbase.core.Jasione;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldInsnNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.InsnNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.TypeInsnNode;
import org.objectweb.asm.tree.analysis.Analyzer;
import org.objectweb.asm.tree.analysis.AnalyzerException;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.List;

public class CommonTransformer {
    public static final Logger LOGGER = LogManager.getLogger();
    public static final String SYNTHETIC_VALUES = "$VALUES"; // generated by the compiler (javac)
    public static final String VALUES_METHOD_NAME = "values";

    public static boolean process(ClassNode node) {
        boolean transformed = false;
        if (NonEnumTransformer.processNonEnum(node)) {
            transformed = true;
        }
        if ((node.access & Opcodes.ACC_ENUM) != 0) {
            EnumTransformer.processEnum(node);
            transformed = true;
        }
        if (transformed) {
            maybeDumpClass(node);
        }
        return transformed;
    }

    private static void maybeDumpClass(ClassNode classNode) {
        if (Jasione.getConfig().dumpClasses) {
            dumpClass(classNode);
        }
    }

    private static void dumpClass(ClassNode classNode) {
        ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_MAXS);
        classNode.accept(writer);
        try {
            var path = Path.of(Constants.OUTPUT_DIR, classNode.name.replace(".", "/") + ".class");
            Files.createDirectories(path.getParent());
            Files.write(path, writer.toByteArray(), StandardOpenOption.CREATE, StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING);
        } catch (IOException e) {
            LOGGER.warn("Failed to dump class {}", classNode.name, e);
        }
    }

    public static class EnumTransformer {
        public static void processEnum(ClassNode node) {
            String arrayDesc = "[L" + node.name + ";";
            String valuesMethodDesc = "()[L" + node.name + ";";
            for (var methodNode : node.methods) {
                if (VALUES_METHOD_NAME.equals(methodNode.name) && valuesMethodDesc.equals(methodNode.desc)) {
                    methodNode.instructions.clear();
                    methodNode.instructions.add(new FieldInsnNode(Opcodes.GETSTATIC, node.name, SYNTHETIC_VALUES, arrayDesc));
                    methodNode.instructions.add(new InsnNode(Opcodes.ARETURN));
                    methodNode.maxStack = 1;
                    methodNode.maxLocals = 0;
                }
            }
        }
    }

    public static class NonEnumTransformer {
        public static boolean processNonEnum(ClassNode node) {
            boolean flag = false;
            for (var methodNode : node.methods) {
                // Process all methods, return true if any of them has been transformed
                if (processMethod(methodNode, node.name)) {
                    flag = true;
                }
            }
            return flag;
        }

        public static boolean processMethod(MethodNode node, String className) {
            if (node.instructions == null || node.instructions.size() == 0) {
                return false;
            }
            return rewriteUnsafeValuesCall(node, className);
        }

        private static boolean rewriteUnsafeValuesCall(MethodNode node, String className) {
            List<MethodInsnNode> valuesInsns = new ArrayList<>();
            for (var insn : node.instructions) {
                if (insn instanceof MethodInsnNode methodInsnNode &&
                        isLikelyEnumValuesCall(methodInsnNode)) {
                    valuesInsns.add(methodInsnNode);
                }
            }

            boolean rewritten = false;
            for (var valuesInsn : valuesInsns) {
                if (!isSafe(node, className, valuesInsn)) {
                    appendCloneToValuesCall(valuesInsn, node);
                    rewritten = true;
                }
            }
            return rewritten;
        }

        private static boolean isSafe(MethodNode node, String className, MethodInsnNode valuesInsn) {
            InterpreterEx interpreterEx = new InterpreterEx(valuesInsn);
            Analyzer<SourceValueEx> analyzer = new Analyzer<>(interpreterEx);
            try {
                analyzer.analyze(className, node);
            } catch (AnalyzerException e) {
                LOGGER.warn("Failed to analyze {}", className, e);
                return false;
            }
            return !interpreterEx.hasViolation();
        }

        private static void appendCloneToValuesCall(MethodInsnNode valuesInsn, MethodNode methodNode) {
            String arrayDesc = valuesInsn.desc.substring(2); // ()[LEnum; -> [LEnum;
            InsnList insnList = new InsnList();
            insnList.add(new MethodInsnNode(Opcodes.INVOKEVIRTUAL, arrayDesc, "clone", "()Ljava/lang/Object;", false));
            insnList.add(new TypeInsnNode(Opcodes.CHECKCAST, arrayDesc));
            methodNode.instructions.insert(valuesInsn, insnList);
        }

        public static boolean isLikelyEnumValuesCall(MethodInsnNode insn) {
            return insn.getOpcode() == Opcodes.INVOKESTATIC &&
                    insn.name.equals(VALUES_METHOD_NAME) &&
                    insn.desc.equals("()[L" + insn.owner + ";"); //TODO
        }
    }
}
